name: TodoApp
description: Uma nova aplicação Flutter.

publish_to: 'none' # Remover esta linha se for publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependências adicionais
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
